export const THEME_COLORS = {
  DEFAULT_BUTTON_BACKGROUND_PRIMARY: '#0A6EFA',
  DEFAULT_BLUE_PRIMARY: '#0A6EFA',
  DEFAULT_BLUE_SECONDARY: '#1e7bfc',
  DEFAULT_INFO_TEXT: '#8a8a8a',
  DEFAULT_LINK_TEXT: 'rgba(0, 55, 107, 1)',
  DEFAULT_INPUT_BACKGROUND: '#EEEEEE',
  DEFAULT_SHADOW: 'rgba(0, 0, 0, 0.64)',
  DEFAULT_GREY_SCALE: 'rgba(242, 242, 246, 1)',
  DANGER_COLOR: '#d7263d',
  WARNING_COLOR: '#fcad23',
  WHITE: '#FFFFFF',
};
